version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - EARTHQUAKE_API_URL=$EARTHQUAKE_API_URL
    ports:
      - "5000:5000"
    command: bash -c "yarn install && yarn start"

  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: bash -c "yarn install && yarn lint && yarn test"
